# Generated by Django 4.1.1 on 2023-06-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particpant',
            name='favorite_book',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='particpant',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
