# Generated by Django 4.1.1 on 2023-06-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_particpant_favorite_book_alter_particpant_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Particpant',
            new_name='Participant',
        ),
    ]
