# Generated by Django 4.1.1 on 2023-07-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formmodel_formrecord_formfield_formdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='record',
            new_name='record_id',
        ),
        migrations.RenameField(
            model_name='formdata',
            old_name='data',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='formrecord',
            name='rid',
        ),
    ]
