# Generated by Django 4.1.1 on 2023-07-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_formdata_form_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrecord',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='record_id',
            field=models.IntegerField(),
        ),
    ]
