# Generated by Django 4.1.1 on 2023-07-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formdata_form_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='form_field_id',
            field=models.IntegerField(default=100),
        ),
    ]
