# Generated by Django 4.1.1 on 2023-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_formrecord_date_alter_formdata_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrecord',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
